"""
analysis/router.py — HTTP layer for voice analysis endpoints.
"""
import asyncio
from fastapi import APIRouter, BackgroundTasks, Depends, File, Form, Request, UploadFile
from fastapi.responses import JSONResponse
from pydantic import BaseModel
from fastapi.concurrency import run_in_threadpool

from auth.deps import get_current_user
from analysis.service import AnalysisError, run_voice_analysis
from analysis.repository import insert_event, mark_viewed, mark_downloaded
from rate_limit.service import enforce, record_usage, get_quota
from config import log

router = APIRouter(prefix="/analysis", tags=["Analysis"])

# GLOBAL SEMAPHORE: Limit ML processing to 1 concurrent request per worker
# This prevents CPU thrashing when 100 users hit the API at once.
ml_semaphore = asyncio.Semaphore(1)

class EngagementRequest(BaseModel):
    session_id: str

@router.post("/voice", summary="Submit voice recording for stress analysis")
async def voice_analysis(
    request:          Request,
    background_tasks: BackgroundTasks,
    audio_file:       UploadFile = File(...),
    sleep_3d_avg:     float      = Form(0.0),
    session_id:       str        = Form(...),
    user:             dict       = Depends(get_current_user),
):
    user_id = user["user_id"]
    email   = user["email"]
    ip      = request.client.host or "unknown"

    enforce(email, ip)

    try:
        audio_bytes = await audio_file.read()
    except Exception as exc:
        log.error(f"[analysis] Failed to read upload: {exc}")
        return JSONResponse(status_code=400, content={
            "detail": f"INVALID_FILE|Could not read the uploaded audio file.",
        })

    # Wait in line without blocking the event loop or Gunicorn heartbeats
    async with ml_semaphore:
        try:
            # Run the heavy CPU math in a background thread so the asyncio loop stays alive
            result = await run_in_threadpool(
                run_voice_analysis, audio_bytes, audio_file.filename or "audio.wav", sleep_3d_avg
            )
        except AnalysisError as exc:
            parts       = str(exc).split("|", 1)
            code        = parts[0] if len(parts) == 2 else "PROCESSING_ERROR"
            msg         = parts[1] if len(parts) == 2 else str(exc)
            status_code = 422 if code in ("INSUFFICIENT_SPEECH", "NO_SEGMENTS") else 500
            return JSONResponse(status_code=status_code, content={
                "detail": f"{code}|{msg}",
            })

    background_tasks.add_task(
        _persist_and_rate_limit, user_id, email, ip, session_id, result
    )

    return result

def _persist_and_rate_limit(
    user_id: str, email: str, ip: str, session_id: str, result: dict
) -> None:
    try:
        import copy
        db_payload = copy.deepcopy(result)
        
        # Extract the hidden summary generated by FLAN-T5
        summary_text = db_payload.pop("_db_summary", None)
        # Ensure it's removed from the actual HTTP response dictionary too
        result.pop("_db_summary", None)
        
        if "overall" in db_payload and isinstance(db_payload["overall"], dict):
            db_payload["overall"]["summary"] = summary_text
            
        event_id = insert_event(user_id, email, ip, session_id, db_payload)
        log.info(f"[analysis] Event saved — id={event_id}, session={session_id}")
    except Exception as exc:
        log.error(f"[analysis] Failed to persist event: {exc}")
    try:
        record_usage(email, ip)
    except Exception as exc:
        log.error(f"[analysis] Failed to record usage: {exc}")


@router.patch("/viewed", summary="Mark analysis result as viewed")
def mark_as_viewed(
    body: EngagementRequest,
    user: dict = Depends(get_current_user),
):
    ok = mark_viewed(body.session_id, user["user_id"])
    if not ok:
        return JSONResponse(status_code=404, content={
            "detail": "Session not found or does not belong to you."
        })
    return {"success": True, "has_viewed_result": True}


@router.patch("/downloaded", summary="Mark analysis result as downloaded")
def mark_as_downloaded(
    body: EngagementRequest,
    user: dict = Depends(get_current_user),
):
    ok = mark_downloaded(body.session_id, user["user_id"])
    if not ok:
        return JSONResponse(status_code=404, content={
            "detail": "Session not found or does not belong to you."
        })
    return {"success": True, "has_clicked_download": True}


@router.get("/quota", summary="Get remaining analysis quota")
def get_analysis_quota(user: dict = Depends(get_current_user)):
    quota = get_quota(user["email"])
    return quota
