name: Deploy Backend to GCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GCP VM
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.GCP_HOST }}
          username: ${{ secrets.GCP_USERNAME }}
          key: ${{ secrets.GCP_SSH_KEY }}
          command_timeout: 30m          # <--- HE MUST ADD THIS LINE
          script: |
            set -e
            echo "🚀 Backend Deployment Started..."
            cd /home/nextyou/sound-check-web-backend
            
            echo "📥 Fetching latest code from GitHub..."
            git fetch --all
            git reset --hard origin/main
            
            echo "📦 Building new Docker Image with Gunicorn & ML Models..."
            docker compose build
            
            echo "🔄 Swapping Containers..."
            docker compose down
            docker compose up -d
            
            echo "🧹 Cleaning up old unused Docker images..."
            docker image prune -f
            
            echo "✅ Backend Deployment Successful!"
